--/*this file is generate by proto2c.lua do not change it by hand*/
require "msg_client"
local MSG_RESNAME={}
MSG_RESNAME[IDUM_Response] = "UM_Response"
MSG_RESNAME[IDUM_Logout] = "UM_Logout"
MSG_RESNAME[IDUM_EnterGame] = "UM_EnterGame"
MSG_RESNAME[IDUM_SyncRole] = "UM_SyncRole"
MSG_RESNAME[IDUM_ItemUpdate] = "UM_ItemUpdate"
MSG_RESNAME[IDUM_Shop] = "UM_Shop"
MSG_RESNAME[IDUM_Hero] = "UM_Hero"
MSG_RESNAME[IDUM_ServerList] = "UM_ServerList"
MSG_RESNAME[IDUM_LoginFightKey] = "UM_LoginFightKey"
MSG_RESNAME[IDUM_RoleInfo] = "UM_RoleInfo"
MSG_RESNAME[IDUM_Fans] = "UM_Fans"
MSG_RESNAME[IDUM_Ranks] = "UM_Ranks"
MSG_RESNAME[IDUM_FightLikes] = "UM_FightLikes"
MSG_RESNAME[IDUM_TopMsg] = "UM_TopMsg"
MSG_RESNAME[IDUM_MsgList] = "UM_MsgList"
MSG_RESNAME[IDUM_Friends] = "UM_Friends"
MSG_RESNAME[IDUM_AddFriend] = "UM_AddFriend"
MSG_RESNAME[IDUM_AddInvite] = "UM_AddInvite"
MSG_RESNAME[IDUM_DelInvite] = "UM_DelInvite"
MSG_RESNAME[IDUM_SeasonRank] = "UM_SeasonRank"
MSG_RESNAME[IDUM_GameRecord] = "UM_GameRecord"
MSG_RESNAME[IDUM_Photos] = "UM_Photos"
return MSG_RESNAME